name: build_and_push

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  build-go:
    needs: checkout-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
      - name: Install go compiler for gRPC
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          export PATH="$PATH:$(go env GOPATH)/bin"
      - name: Build
        run: |
          mkdir -p jagw-go
          protoc --proto_path=. --go_out=./jagw-go --go_opt=paths=import --go-grpc_out=./jagw-go --go-grpc_opt=paths=import **/*.proto
          cp readme-compiled/go-readme.md jagw-go/github.com/jalapeno-api-gateway/protobuf/jagw/README.md
      - name: Push
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'jagw-go/github.com/jalapeno-api-gateway/protobuf/jagw/'
          destination-github-username: 'jalapeno-api-gateway'
          destination-repository-name: 'protorepo-jagw-go'
          user-email: michel_bongard@hotmail.com
          target-branch: main
          commit-message: 'updating protobuf definitions'
  build-node:
    needs: checkout-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
      - name: Install node compiler for gRPC
        run: npm install -g grpc-tools
      - name: Build
        run: |
          mkdir -p jagw-node
          grpc_tools_node_protoc --js_out=import_style=commonjs,binary:jagw-node --grpc_out=grpc_js:jagw-node $(find . -iname "*.proto")
          cp readme-compiled/node-readme.md jagw-node/README.md
      - name: Push
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'jagw-node/'
          destination-github-username: 'jalapeno-api-gateway'
          destination-repository-name: 'protorepo-jagw-node'
          user-email: michel_bongard@hotmail.com
          target-branch: main
          commit-message: 'updating protobuf definitions'
