name: build_and_push_dev

on:
  push:
    branches-ignore:
      - 'main'

  workflow_dispatch:

jobs:
  build-go:
    env:
      working-directory: /temp/go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout protorepo
        uses: actions/checkout@v2
        with:
          path: ${{env.working-directory}}/protorepo
      - name: Checkout protorepo-jagw-go
        uses: actions/checkout@v2
        with:
          repository: jalapeno-api-gateway/protorepo-jagw-go
          path: ${{env.working-directory}}/protorepo-jagw-go
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
      - name: Install go compiler for gRPC
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          export PATH="$PATH:$(go env GOPATH)/bin"
      - name: Build
        run: |
          cd ${{env.working-directory}}/protorepo
          mkdir -p jagw
          protoc --proto_path=. --go_out=./jagw --go_opt=paths=import --go-grpc_out=./jagw --go-grpc_opt=paths=import **/*.proto
      - name: Initialize Module
        run: |
          cd ${{env.working-directory}}/protorepo/jagw/github.com/jalapeno-api-gateway/protobuf/
          go mod init github.com/jalapeno-api-gateway/protorepo-jagw-go
          go mod tidy
      - name: Get branch name
        shell: bash
        run: |
          cd ${{env.working-directory}}/protorepo
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch
      - name: Ensure branch exists on remote repository
        env:
          branch: dev-${{ steps.get_branch.outputs.branch }}
        run: |
          cd ${{env.working-directory}}/protorepo-jagw-go
          (git show-branch ${{env.branch}} &>/dev/null) && (git checkout ${{env.branch}}) && (git push origin ${{env.branch}})
      - name: Push
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ${{env.working-directory}}/protorepo/jagw/github.com/jalapeno-api-gateway/protobuf/
          destination-github-username: 'jalapeno-api-gateway'
          destination-repository-name: 'protorepo-jagw-go'
          user-email: michel_bongard@hotmail.com
          target-branch: dev-${{ steps.get_branch.outputs.branch }}
          commit-message: 'updating protobuf definitions'
