name: build_artifacts

on:
  release:
    types: [published]

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.17.3'
      - name: Install protoc-gen-grpc-web
        run: |
          wget https://github.com/grpc/grpc-web/releases/download/1.3.0/protoc-gen-grpc-web-1.3.0-linux-x86_64
          sudo mv protoc-gen-grpc-web-1.3.0-linux-x86_64 /usr/local/bin/protoc-gen-grpc-web
          chmod +x /usr/local/bin/protoc-gen-grpc-web
      - name: Install node compiler for gRPC
        run: npm i grpc-web google-protobuf
      - name: Build
        run: |
          mkdir -p jagw
          protoc --js_out=import_style=commonjs,binary:jagw --grpc-web_out=import_style=typescript,mode=grpcwebtext:jagw $(find . -iname "*.proto")
          zip -r nodejs-${{ steps.get_release.outputs.tag_name }}.zip jagw
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./nodejs-${{ steps.get_release.outputs.tag_name }}.zip
          asset_name: nodejs-${{ steps.get_release.outputs.tag_name }}.zip
          asset_content_type: application/zip
