name: build_golang

on:
  release:
    types: [published]
  
jobs:
  build-push-golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
      - name: Install go compiler for gRPC
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          export PATH="$PATH:$(go env GOPATH)/bin"
      - name: Build
        run: |
          mkdir -p jagw
          protoc --proto_path=. --go_out=./jagw --go_opt=paths=import --go-grpc_out=./jagw --go-grpc_opt=paths=import **/*.proto
      - name: Initialize Module
        run: |
          cd jagw/github.com/jalapeno-api-gateway/protobuf/
          go mod init github.com/jalapeno-api-gateway/protorepo-jagw-go
          go mod tidy
          cd ../../../..
      - name: Create README
        run: |
          echo "# protorepo-jagw-go" >> jagw/github.com/jalapeno-api-gateway/protobuf/README.md
          echo "This repository contains the compiled code for the Jalapeño API Gateway for **golang**." >> jagw/github.com/jalapeno-api-gateway/protobuf/README.md
      - name: Push
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'jagw/github.com/jalapeno-api-gateway/protobuf/'
          destination-github-username: 'jalapeno-api-gateway'
          destination-repository-name: 'protorepo-jagw-go'
          user-email: michel_bongard@hotmail.com
          target-branch: main
          commit-message: 'updating protobuf definitions'
  release-golang:
    needs: build-push-golang
    name: Create Release for golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: 'jalapeno-api-gateway/protorepo-jagw-go'
          token: ${{ secrets.API_TOKEN_ALLOW_ALL }}
        env:
          GITHUB_REPOSITORY: 'jalapeno-api-gateway/protorepo-jagw-go'
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_ALLOW_ALL }}
