name: build_and_push_dev

on:
  push:
    branches-ignore:
      - 'main'

  workflow_dispatch:

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout protorepo
        uses: actions/checkout@v2
        with:
          path: protorepo
      - name: Checkout protorepo-jagw-go
        uses: actions/checkout@v2
        with:
          repository: jalapeno-api-gateway/protorepo-jagw-go
          path: protorepo-jagw-go
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
      - name: Install go compiler for gRPC
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          export PATH="$PATH:$(go env GOPATH)/bin"
      - name: Build
        run: |
          cd protorepo
          mkdir -p jagw
          protoc --proto_path=. --go_out=./jagw --go_opt=paths=import --go-grpc_out=./jagw --go-grpc_opt=paths=import **/*.proto
          cd ..
      - name: Initialize Module
        run: |
          cd protorepo/jagw/github.com/jalapeno-api-gateway/protobuf/
          go mod init github.com/jalapeno-api-gateway/protorepo-jagw-go
          go mod tidy
          cd ../../../../..
      - name: Get branch name
        shell: bash
        run: |
          cd protorepo
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          cd ..
        id: get_branch
      - name: Prepare remote repo
        run: |
          cd protorepo-jagw-go
          git init
          git config user.email "michel_bongard@hotmail.com"
          git config user.name "mbongard"
          git remote add deploy "https://mbongard:github.com/jalapeno-api-gateway/protorepo-jagw-go"
          git checkout -b dev-${{ steps.get_branch.outputs.branch }}
          cp -r ../protorepo/jagw/github.com/jalapeno-api-gateway/protobuf/ .
          git add .
          git commit -am "updating protobuf definitions"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: protorepo-jagw-go
          branch: dev-${{ steps.get_branch.outputs.branch }}
          force: true
