# This is a basic workflow to help you get started with Actions

name: create_releases_for_compiled_repos

on:
  release:
  
jobs:
  release-go:
    name: Create Release for golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          owner: 'jalapeno-api-gateway'
          repo: 'protorepo-jagw-go'
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
