# This is a basic workflow to help you get started with Actions

name: create_releases_for_compiled_repos

on:
  release:
    types: [published]
  
jobs:
  release-go:
    name: Create Release for golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          token: ${{ secrets.API_TOKEN_GITHUB }}
        env:
          GITHUB_REPOSITORY: jalapeno-api-gateway/protorepo-jagw-go
